apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2019-10-25T17:53:21Z"
    labels:
      app: grafana
      chart: grafana-3.10.2
      heritage: Tiller
      release: grafana
    name: grafana
    namespace: monitoring
    resourceVersion: "48194051"
    selfLink: /api/v1/namespaces/monitoring/services/grafana
    uid: 55b54163-f750-11e9-8637-06fdaf51968e
  spec:
    clusterIP: 10.102.18.206
    ports:
    - name: service
      port: 80
      protocol: TCP
      targetPort: 3000
    selector:
      app: grafana
      release: grafana
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
