sidecar:
  image: xuxinkun/k8s-sidecar:0.0.7
  imagePullPolicy: IfNotPresent
  datasources:
    enabled: true
    label: grafana_datasource
#  serverDashboardConfigmaps:
#    - grafana-prometheus-overview-dashboard
  dashboards:
    enabled: true
    label: grafana_dashboard

#  [sidecar-definition]
#  dashboardProviders:
#    dashboardproviders.yaml:
#      apiVersion: 1
#      providers:
#      - name: 'default'
#        orgId: 1
#        folder: ''
#        type: file
#        disableDeletion: false
#        editable: true
#        options:
#          path: /var/lib/grafana/dashboards/default
#
#  dashboards:
#    default:
#      node-exporter:
#        gnetId: 1860
#        revision: 14
#        datasource: Prometheus
